name: Build and Push

on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        required: true
        type: string
    inputs:
      registry:
        required: true
        type: string
        default: ghcr.io
      username:
        required: true
        type: string
        default: ${{ github.actor }}
      password:
        required: true
        type: string
        default: ${{ secrets.GITHUB_TOKEN }}
      image:
        required: true
        type: string

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      -
        name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }}
          password: ${{ inputs.password }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ inputs.registry }}/${{ inputs.image }}
