name: Build and Push to ghcr.io

on:
  workflow_call:
    inputs:
      prefix:
        required: true
        type: string

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      contexts: ${{ steps.detect_changes.outputs.contexts }}
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect modified directories
      id: detect_changes
      run: |
        # Fetch the commit history to ensure we compare properly
        git fetch --depth=2

        # Find the changed directories
        CHANGED_DIRS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '^(2023|2024)/' | awk -F'/' '{print $1"/"$2}' | sort -u)

        # Check for Dockerfile in each directory
        DOCKER_CONTEXTS=()
        for DIR in $CHANGED_DIRS; do
          if [[ -f "$DIR/Dockerfile" ]]; then
            DOCKER_CONTEXTS+=("$DIR")
          fi
        done

        # If Dockerfile found, set output
        if [ ${#DOCKER_CONTEXTS[@]} -gt 0 ]; then
          echo "contexts=${DOCKER_CONTEXTS[*]}" >> $GITHUB_OUTPUT
        else
          echo "contexts=none" >> $GITHUB_OUTPUT
        fi

  build:
    name: Build and Push
    runs-on: ubuntu-latest
    strategy:
      matrix:
        context: ${{ fromJson(needs.detect.outputs.contexts) }}
    steps:

      - uses: actions/checkout@v3

      -
        name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          push: true
          tags: ghcr.io/${{ inputs.prefix }}${{ matrix.context }}:${{ github.sha }}
